runtime: php81

handlers:
  - url: /.*
    script: auto

env_variables:
  DB_HOST: "104.154.99.108"
  DB_USER: "root"
  DB_PASS: "Scout1st"
  DB_NAME: "applicationdb"

automatic_scaling:
  min_instances: 1
  max_instances: 10
