runtime: php81

handlers:
  - url: /add_user\.php
    script: add_user.php

  - url: /view_users\.php
    script: view_users.php

  - url: /.*
    script: index.php

env_variables:
  DB_HOST: "35.225.245.211"
  DB_USER: "root"
  DB_PASS: "Scout1st"
  DB_NAME: "alpha_db"

automatic_scaling:
  min_instances: 1
  max_instances: 10

