steps:
  # Step 1: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Specify the logs bucket for storing build logs
logs_bucket: 'gs://my-build-logs'

# Optional: Define a timeout for the build
timeout: '1200s'
