name: Deploy to Google Cloud Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.11.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.7.0
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Submit build request
      run: |
        gcloud builds submit --config cloudbuild.yaml .
